GET  http://localhost:3000

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"test user",
    "password": "password",
    "email": "test@test.com"
}

###
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email":"test@test.com",
    "password": "password"
}
###
GET http://localhost:3000/tracked-products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mzg4OGQ3Zi03YmRmLTQyNjMtYmRiMS01ZWEzYzYwZGZjZDUiLCJpYXQiOjE3OTA1ODM2MjAsImV4cCI6MTc5MTE4ODQyMH0.dJGzJBGaT3KCdF0p9LKHd27pN9u6jzkUB8vPC29yK7M