GET  http://localhost:3000

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"test",
    "password": "password",
    "email": ""
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"email",
    "password": "password"
}
###
GET http://localhost:3000/products/tracked-products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mzg4OGQ3Zi03YmRmLTQyNjMtYmRiMS01ZWEzYzYwZGZjZDUiLCJpYXQiOjE3OTA2OTQ5MjcsImV4cCI6MTc5MTI5OTcyN30.tgbm_ZfTo3Gf1jiu9hxGFziMRkaMzIq5sSYfipuQdoc
//tesrt user

###
POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YmM3M2FiOS1jZTQ2LTQwYjMtOTJjYy1iMWZhMGUzYTQ1NTAiLCJpYXQiOjE3OTExMTQzNzYsImV4cCI6MTc5MTcxOTE3Nn0.xJ9ArtJWnIRPCF_5VlASznA7bN2Vb4PJrkXNUqcWCzo
Content-Type: application/json

{
    "link": "https://www.daraz.lk/products/western-digital-sn850x-1tb-2tb-4tb-wd_black-m2-2280-nvme-pcie-gen-40x4-ssd-solid-state-drives-for-gaming-computer-laptop-ps5-i403881606-s2153023336.html?",
    "target": 100000
}